export const expectedErroMessageOnMandatoryFields = [
  'This field is required',
  'This field is required',
  'Please select a value',
  'Please select a value',
  'Please select a value',
  'Please enter address line 1',
  'Please select a value',
  'This field is required',
  'This field is required',
  'Alternate address is required',
  'City is required',
  'State is required',
  'Zip code is required'
]

export const expectedTitleDropDown = [
  'Mx.',
  'Mr.',
  'Mrs.',
  'Miss.',
  'Ms.',
  'Mstr.',
  'Dr.',
  'Prof.',
  'Rev.',
  'Sir',
  'Sister'
]

export const expectedTitleDropDownTestIds = [
  'Mx.',
  'Mr.',
  'Mrs.',
  'Miss.',
  'Ms.',
  'Mstr.',
  'Dr.',
  'Prof.',
  'Rev.',
  'Sir',
  'Sister'
]

export const expectedSexBiologicalDropDown = ['Male', 'Female', 'Unknown']

export const expectedBloodGroupDropDown = [
  'A+',
  'B+',
  'O+',
  'AB+',
  'A-',
  'B-',
  'O-',
  'AB-'
]

export const expectedEthnicityDropDown = [
  'Hispanic or Latino',
  'Not Hispanic or Latino',
  'Andalusian',
  'Argentinean',
  'Asturian',
  'Belearic Islander',
  'Bolivian',
  'Canal Zone',
  'Canarian',
  'Castillian',
  'Catalonian',
  'Central American',
  'Central American Indian',
  'Chicano',
  'Chilean',
  'Colombian',
  'Criollo',
  'Costa Rican',
  'Cuban',
  'Dominican',
  'Ecuadorian',
  'Gallego',
  'Guatemalan',
  'Honduran',
  'La Raza',
  'Latin American',
  'Mexican',
  'Mexican American',
  'Mexican American Indian',
  'Nicaraguan',
  'Panamanian',
  'Paraguayan',
  'Peruvian',
  'Puerto Rican',
  'Salvadoran',
  'South American',
  'South American Indian',
  'Spaniard',
  'Spanish Basque',
  'Uruguayan',
  'Valencian',
  'Venezuelan',
  'Declined to Specify',
  'Patient Uncertain',
  'Prohibited by State Law'
]

export const expectedReligionDropDown = [
  'Adventist',
  'African Religions',
  'Afro-Caribbean Religions',
  'Agnostic',
  'Agnosticism',
  'Anglican',
  'Animism',
  'Assembly of God',
  'Atheism',
  "Babi and Baha'I Faiths",
  'Baptist',
  'Bon',
  'Born Again',
  'Brethren',
  'Cao Dai',
  'Celticism',
  'Christian',
  'Christian Scientist',
  'Church of Christ',
  'Church of God',
  'Confucianism',
  'Congregational',
  'Cyberculture Religions',
  'Disciples of Christ',
  'Divination',
  'Eastern Orthodox',
  'Episcopalian',
  'Evangelical Covenant',
  'Fourth Way',
  'Free Daism',
  'Friends',
  'Full Gospel',
  'Gnosis',
  'Greek Orthodox',
  'Hinduism',
  'Humanism',
  'Independent',
  'Interdenominational',
  'Islam',
  'Jainism',
  "Jehovah's Witnesses",
  'Jewish Orthodox',
  'Judaism',
  'Latter Day Saints',
  'Lutheran',
  'Mahayana',
  'Meditation',
  'Messianic Judaism',
  'Methodism',
  'Mitraism',
  'Mormon',
  'Native American',
  'Nazarene',
  'New Age',
  'Non-Roman Catholic',
  'Occult',
  'Orthodox',
  'Paganism',
  'Pentecostal',
  'Presbyterian',
  'Protestant',
  'Protestant, No Denomination',
  'Reformed',
  'Reformed Presbyterian',
  'Roman Catholic Church',
  'Russian Orthodox',
  'Salvation Army',
  'Satanism',
  'Scientology',
  'Shamanism',
  'Shiite (Islam)',
  'Shinto',
  'Sikism',
  'Spiritualism',
  'Sunni (Islam)',
  'Taoism',
  'The Process',
  'Theravada',
  'Unitarian Universalist',
  'Unitarian-Universalism',
  'United Church of Christ',
  'Universal Life Church',
  'Vajrayana (Tibetan)',
  'Veda',
  'Voodoo',
  'Wicca',
  'Yaohushua',
  'Zen Buddhism',
  'Zoroastrianism',
  'Unknown',
  'Choose not to disclose'
]

export const expectedRaceDropDown = [
  'Hispanic (Mexican/Mexamer/Chicano)',
  'Hispanic (Puerto Rican)',
  'Hispanic (Cuban)',
  'Hispanic (Central/South American)',
  'Hispanic – Other (Born outside the USA)',
  'Hispanic – Other (Born in the USA)',
  'Hispanic (Unspecified)',
  'White American',
  'Native American or Alaskan Native',
  'Middle Eastern American',
  'Black or African American',
  'American Indian',
  'Asian (Unspecified)',
  'Asian (Specified)',
  'Asian (Chinese)',
  'Asian (Japanese)',
  'Asian (Korean)',
  'Asian (Vietnamese)',
  'Asian (Cambodian)',
  'Asian (Thai)',
  'Asian (Laotian)',
  'Asian (Hmong)',
  'Asian',
  'Indian (Not American Indian)',
  'Filipino',
  'Hawaiian',
  'Guamanian',
  'Samoan',
  'Eskimo',
  'Aleut',
  'Pacific Islander',
  'Multiracial',
  'Withheld',
  'Unknown',
  'Choose not to disclose'
]

export const expectedPreferredLanguageDropDown = [
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Baptist',
  'Bulgarian',
  'Catalan',
  'Cebuano',
  'Chichewa',
  'Chinese',
  'Corsican',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Esperanto',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'Frisian',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Haitian Creole',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Icelandic',
  'Igbo',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Kinyarwanda',
  'Korean',
  'Kurdish (Kurmanji)',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Mongolian',
  'Myanmar (Burmese)',
  'Nepali',
  'Norwegian',
  'Odia (Oriya)',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Romanian',
  'Russian',
  'Samoan',
  'Scots Gaelic',
  'Serbian',
  'Sesotho',
  'Shona',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu',
  'Unknown',
  'Choose not to disclose'
]

export const expectedWorkStatusDropDown = [
  'Employed',
  'Unemployed',
  'Self Employed',
  'Student Full-Time',
  'Student Part-Time',
  'Retired',
  'Disabled',
  'Unknown',
  'Choose not to disclose'
]

export const expectedCountryDropDown = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas (the)',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory (the)',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands (the)',
  'Central African Republic (the)',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands (the)',
  'Colombia',
  'Comoros (the)',
  'Congo (the Democratic Republic of the)',
  'Congo (the)',
  'Cook Islands (the)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic (the)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (the) [Malvinas]',
  'Faroe Islands (the)',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories (the)',
  'Gabon',
  'Gambia (the)',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (the)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic (the)",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands (the)',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (the)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger (the)',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Mariana Islands (the)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines (the)',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russian Federation (the)',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan (the)',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic (the)',
  'Taiwan (Province of China)',
  'Tajikistan',
  'Tanzania, the United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (the)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates (the)',
  'United Kingdom of Great Britain and Northern Ireland (the)',
  'United States Minor Outlying Islands (the)',
  'United States of America (the)',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara*',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands'
]

export const phoneNumberTypeDropDown = [
  'Office',
  'Office Fax',
  'Home',
  'Home Fax',
  'Mobile',
  'Private'
]

export const phoneNumberTypeDropDownTestIds = [
  'office',
  'office_fax',
  'home',
  'home_fax',
  'mobile',
  'private'
]
