# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['windows-2022']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0-alpha - 3.9.0' # SemVer's version range syntax
      - name: Run the test on windows
        if: matrix.os == 'windows-2022'
        run: |
          pip install -r requirements.txt
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager
          robot .//feature//

