name: Build of pull request

on:
  - pull_request

jobs:
  e2e:
    runs-on: windows-2022
    steps:
      - name: Checkout Automation Repository
        uses: actions/checkout@v2
        with:
          repository: houseworksinc/emr-frontend-automation
          ref: RuchetaG-patch-2
          token: ${{ secrets.QA_WORKFLOW }}
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0-alpha - 3.9.0' # SemVer's version range syntax
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Install robot framework
        run: pip install robotframework
      - name: Install robot framework selenium library
        run: pip install robotframework-seleniumlibrary
      - name: Install robot framework parallel bot
        run: pip install robotframework-pabot
      - name: Install robot framework webdriver manager for automatic driver download
        run: pip install webdriver-manager
      - name: Run tests
        run: robot .//feature//
